### ISSUE TITLE
Issues with control spacing, color, and state on Ubuntu 16.04 LTS (Unity + GTK 3.0+)

### ISSUE THREAD

**Issue by Bonfire** [fuegowolf/dotfiles#1]
I've installed the arc-firark them on my Ubuntu 16.04 LTS machine and noticed that I ran into some issues with specific components/controls on my windows. You can see below some of the issues.

![screenshot from 2018-07-07 22-58-30](https://user-images.githubusercontent.com/5704760/42416329-cffc7176-8239-11e8-9bc1-01f679218e47.png)
Here you can see the tabs at the top do not have any defined borders, and have zero spacing.

![screenshot from 2018-07-07 23-00-06](https://user-images.githubusercontent.com/5704760/42416334-e85506ca-8239-11e8-92e8-3e5f50c0ab81.png)
Here you can see the -/+ control not having any defined borders, and the transparency value picker being nearly invisible

![screenshot from 2018-07-07 23-00-51](https://user-images.githubusercontent.com/5704760/42416341-05fa3dee-823a-11e8-8e16-6de28cf2ec98.png)
Here you can see the ON/OFF toggled button having no borders, and the groupings for the shortcuts have a nearly invisible border.

I'm not sure if these issues are only appearing for me, but I figured I'd create an issue just to make sure. I'm also not sure if this theme is for bspwm only. I'm running Ubuntu 16.04 LTS with GTK 3.0+ and Unity as my window manager. Any insight or assistance is appreciated.

**Comment by fuegoio** [comment]
Hi !

Thank you for the issue and your interest in my theme, this seems weird you are right. Below is what I have with *AWF*, an app to test GTK (I use GTK 3.0 here) : 

![image](https://user-images.githubusercontent.com/321778/42417094-7770815e-82b2-11e8-9a0b-77327c2e54d4.png)

As you can see, and as I see everywhere in my environment (in PCManFM for example, my file manager), the tabs are spaced and colored, the buttons are correct (look at the - / + here) and borders are present, even if they are very thin and not very bright (I can change that I think).

So in my opinion it should be something with your setup, but is the Arc Dark theme working normally ? My theme is based on it, and appart from the colors I didn't change much.

**Comment by Bonfire** [comment]
Arc-Dark theme works with no issues whatsoever.
![screenshot from 2018-07-08 02-13-12](https://user-images.githubusercontent.com/5704760/42417292-8f589422-8254-11e8-9dba-7aa517fbacd6.png)

I'm on a near fresh install of Ubuntu, but I'm sure that I messed something up along the way. Any ideas what it might be? Or should I close this?

**Comment by fuegoio** [comment]
What is your GTK-3.0 config ? It is in `~/.config/gtk-3.0/settings.ini`, mine looks like this : 

```
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=Arc-Firark
gtk-icon-theme-name=Arc
gtk-cursor-theme-name=DMZ-Black
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
gtk-font-name=Cantarell 11
```

**Comment by Bonfire** [comment]
I've fired up a new instance of Ubuntu to try and get to the bottom of this. Immediately after installing, I placed the settings.ini you provided into my `~/.config/gtk-3.0/settings.ini` folder, and placed the Arc-FirArk theme into the `~/.themes` folder. After doing so, I'm still running into the same issues above. I've also tried placing the `.gtkrc-2.0` file into `~/.gtkrc-2.0` and the issue persisted. I'm not sure if I need the `.gtkrc-2.0` file there or not because I'm using gtk-3.0, but I figured I'd try it regardless. Am I missing anything?

EDIT:
Figured that given that the theme was an edit of the arc-theme, that installing the arc-theme might help remedy the issue but it did not.

**Comment by fuegoio** [comment]
I really don't know ahah, it works on my laptop even with the default Arc Theme not installed at all.

I think that Unity might be messing with this, but I clearly don't see how as my theme is the Arc Theme but with different colors ... Maybe you should try to compile it yourself with https://github.com/erikdubois/Arc-Theme-Colora with my colors if you like them.

**Comment by Bonfire** [comment]
I'll hold off on figuring it out for now and close this. It's very possible, like you said, that it might be Unity messing with it. Thank you very much for the assistance regardless! Oh, and thank you so much for this repo.
